title: "Quarto Testing"
author: "Margo Weber"
date: "03-06-2024"

project:
  type: website
  render:
    - home.qmd
    - about.qmd
    - labs.qmd
    - project.qmd
    - presentation.qmd
  output-dir: docs 
  
metadata-files:
  - _website.yml
  - _metadata.yml

editor: visual
